# Generated by Django 3.2.6 on 2021-08-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diplomas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diploma_name', models.CharField(max_length=200)),
                ('diploma_img', models.ImageField(upload_to='diplomas')),
                ('diploma_category', models.CharField(default='Python', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=200)),
                ('work_img', models.ImageField(upload_to='realisations')),
                ('work_description', models.TextField()),
            ],
        ),
    ]
