# Generated by Django 3.2.6 on 2021-08-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='work_link_github',
            field=models.URLField(default=None),
        ),
    ]
