# Generated by Django 3.2.6 on 2021-08-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_works_work_link_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='work_date',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
